services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cars_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./apps/backend
    restart: unless-stopped
    environment:
      DATABASE_TYPE: postgres
      DATABASE_URL: postgresql://postgres:postgres@db:5432/cars_manager
    depends_on:
      db:
        condition: service_healthy

  frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
