services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cars_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./apps/backend
    environment:
      DATABASE_TYPE: postgres
      DATABASE_URL: postgresql://postgres:postgres@db:5432/cars_manager
      JWT_SECRET: "development-secret-key-at-least-32-chars-long"
      ALLOWED_ORIGINS: '["http://localhost", "http://localhost:4200", "http://localhost:80"]'
      REGISTRATION_TOKEN: "secret-family-token"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
